networks:
  selenoid_network:
    driver: bridge
services:
  api-tests:
    build:
      dockerfile: Dockerfile-api
    container_name: api-tests
    environment:
      - ENV=staging
    volumes:
      - ./allure/api-tests/results:/app/transportsystem.autotesting.api/target/allure-results
  ui-tests:
    container_name: ui-tests
    build:
      dockerfile: Dockerfile-ui
    networks:
      - selenoid_network
    depends_on:
      - selenoid
    volumes:
      - ./allure/ui-tests/results:/app/transportsystem.autotesting.ui/target/allure-results
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - ./transportsystem.autotesting.ui/src/test/resources/selenoid-config:/etc/selenoid
      - ./transportsystem.autotesting.ui/src/test/resources/selenoid_config/video:/opt/selenoid/video
      - ./transportsystem.autotesting.ui/src/test/resources/selenoid_config/logs:/opt/selenoid/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./transportsystem.autotesting.ui/src/test/resources/selenoid_config/video
    shm_size: "2g"
    command: [ "-conf", "/etc/selenoid/browsers.json", "-container-network", "transport-system-auto-tests_selenoid_network", "-limit", "10", "-retry-count", "2", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-session-attempt-timeout", "3m", "-service-startup-timeout", "3m"]
    networks:
      - selenoid_network
  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui:latest"
    networks:
      - selenoid_network
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
  allure-docker-service:
    image: "frankescobar/allure-docker-service"
    container_name: allure-docker-service
    user: 1000:1000
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 15
    ports:
      - "5050:5050"
    volumes:
      - ./allure:/app/projects
    networks:
      - selenoid_network
  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    container_name: test-execution-report
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
    depends_on:
      - allure-docker-service
    networks:
      - selenoid_network