FROM maven:3.8.3-openjdk-17
WORKDIR /app
COPY ./transportsystem.autotesting.core/pom.xml /app/transportsystem.autotesting.core/
COPY ./transportsystem.autotesting.api/pom.xml /app/transportsystem.autotesting.api/
COPY ./transportsystem.autotesting.ui/pom.xml /app/transportsystem.autotesting.ui/
COPY ./pom.xml /app
CMD ["mvn", "clean", "test", "-pl", "transportsystem.autotesting.api", "-am"]