FROM maven:3.8.3-openjdk-17
WORKDIR /app
COPY ./transportsystem.autotesting.core/ transportsystem.autotesting.core/
COPY ./transportsystem.autotesting.api/ transportsystem.autotesting.api/
COPY ./transportsystem.autotesting.ui/ transportsystem.autotesting.ui/
COPY ./pom.xml /app
COPY start_ui_tests_script.sh /start_ui_tests_script.sh
RUN chmod +x /start_ui_tests_script.sh
CMD ["/start_ui_tests_script.sh"]